version: '3'
services:
  postgres:
    build: dockerfiles/postgres
    restart: 'no'
    ports:
    - "5432:5432"
    environment:
      POSTGRES_DB: prisma
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres: ~
