/* eslint-disable */
/* This is an autogenerated file. Do not edit this file directly! */
export type ViewerQuery = {
    viewer: ({
        id: string;
        name: string;
        status: string;
    }) | null;
};
export type ViewerQueryVariables = {};
